// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are only configured for web in this project.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCfcn_q14Wc-AnYPshuJWHtAEzP_Jxf3Bo",
    authDomain: "bright-weddings-605e7.firebaseapp.com",
    projectId: "bright-weddings-605e7",
    storageBucket: "bright-weddings-605e7.firebasestorage.app",
    messagingSenderId: "319657689155",
    appId: "1:319657689155:web:5520ffe43786f325e0d4f6",
    measurementId: "G-FEK846FS4T",
  );
}