import 'package:flutter/material.dart';

final Color backgroundColor = Color(0xFFFFFCF1);
final Color footerColor = Color(0xFFDFE8ED);
final Color footerTitleColor = Color(0xFFFF166C);
final Color gradient1Color = Color(0xFFFFEEB2);
final Color gradient2Color = Color(0xFFF3D48A);
final Color textColor = Color(0xFF66451C);
final Color borderColor = Color(0xFFDEE2E6);
final Color darkBorderColor = Color(0xFF858890);
final Color buttonColor = Color(0xFF607D8B);
final Color footerTextColor = Color(0xFF607D8B);
final Color whatsappColor = Color(0xFF25d366);
final Color greenColor = Color(0xFF198754);
final Color twitterColor = Color(0xFF55ACEE);
final Color facebookColor = Color(0xFF3B5998);
final Color youtubeColor = Color(0xFFD42428);
final Color dashboardSelectedColor = Color(0xFF03B0F7);
final Color dashboardSelectedOneColor = Color(0xFFE4F1FC);
final Color dashboardSelectedTwoColor = Color(0xFFF7FBFE);
final Color headerTitleColor = Color(0xFF433506);
final Color darkYellowColor = Color(0xFFF6AF04);
final Color otherTextColor = Color(0xFFAB8342);
final Color ratingDot1 = Color(0xFFF8896B);
final Color ratingDot2 = Color(0xFF84E8F5);
final Color ratingDot3 = Color(0xFFFFBD66);
final Color ratingDot4 = Color(0xFF52459D);
