final List<Map<String, dynamic>> userList = [
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/3.jpg',
    'video': 'https://example.com/video1.mp4',
    'full_name': 'Julia Ann',
    'address': 'New York',
    'age': '22',
    'gender': 'female',
    'cast': 'Hindu',
    'sub_cast': 'Maratha',
    'devak': 'Lotus',
    'ras': 'Leo',
    'gan': 'Dog',
    'phone_number': '1234567890',
    'education': 'B.Tech (CSE)',
    'demands': 'Looking for a well-settled partner',
    'job': 'Software Engineer',
    'height': '5\'6"',
    'about': 'A kind-hearted and ambitious individual.',
    'email': 'julia.ann@example.com',
    'fathers_name': 'Mr. Ann',
    'mothers_name': 'Mrs. Ann',
    'family_type': 'Joint family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/men1.jpg',
    'video': '',
    'full_name': 'John Doe',
    'address': 'San Francisco',
    'age': '28',
    'gender': 'male',
    'cast': 'Christian',
    'sub_cast': 'Catholic',
    'devak': 'Oak Tree',
    'ras': 'Taurus',
    'gan': 'Elephant',
    'phone_number': '0987654321',
    'education': 'M.S. (Mechanical Engineering)',
    'demands': 'Looking for a well-settled partner',
    'job': 'Mechanical Engineer',
    'height': '6\'1"',
    'about': 'A determined and responsible individual.',
    'email': 'john.doe@example.com',
    'fathers_name': 'Mr. Doe',
    'mothers_name': 'Mrs. Doe',
    'family_type': 'Nuclear family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/4.jpg',
    'video': 'https://example.com/video2.mp4',
    'full_name': 'Sophia Brown',
    'address': 'Los Angeles',
    'age': '25',
    'gender': 'female',
    'cast': 'Muslim',
    'sub_cast': 'Sunni',
    'devak': 'Moon',
    'ras': 'Gemini',
    'gan': 'Horse',
    'phone_number': '2345678901',
    'education': 'B.A. (English)',
    'demands': 'Seeking a partner who values family',
    'job': 'Teacher',
    'height': '5\'4"',
    'about': 'A caring and family-oriented individual.',
    'email': 'sophia.brown@example.com',
    'fathers_name': 'Mr. Brown',
    'mothers_name': 'Mrs. Brown',
    'family_type': 'Joint family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/men4.jpg',
    'video': '',
    'full_name': 'Michael Smith',
    'address': 'Chicago',
    'age': '30',
    'gender': 'male',
    'cast': 'Hindu',
    'sub_cast': 'Brahmin',
    'devak': 'Peepal Tree',
    'ras': 'Aries',
    'gan': 'Lion',
    'phone_number': '3456789012',
    'education': 'PhD (Physics)',
    'demands': '',
    'job': 'Physicist',
    'height': '5\'9"',
    'about': 'A highly intellectual and curious person.',
    'email': 'michael.smith@example.com',
    'fathers_name': 'Mr. Smith',
    'mothers_name': 'Mrs. Smith',
    'family_type': 'Nuclear family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'Emma Johnson',
    'address': 'Houston',
    'age': '24',
    'gender': 'female',
    'cast': 'Christian',
    'sub_cast': 'Protestant',
    'devak': 'Rose',
    'ras': 'Cancer',
    'gan': 'Swan',
    'phone_number': '4567890123',
    'education': 'B.Sc (Biology)',
    'demands': 'Prefers a partner who loves nature',
    'job': 'Biologist',
    'height': '5\'5"',
    'about': 'An environmentally conscious person.',
    'email': 'emma.johnson@example.com',
    'fathers_name': 'Mr. Johnson',
    'mothers_name': 'Mrs. Johnson',
    'family_type': 'Joint family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': 'https://example.com/video3.mp4',
    'full_name': 'Ava Williams',
    'address': 'Phoenix',
    'age': '27',
    'gender': 'female',
    'cast': 'Hindu',
    'sub_cast': 'Vaishya',
    'devak': 'Sunflower',
    'ras': 'Leo',
    'gan': 'Tiger',
    'phone_number': '5678901234',
    'education': 'MBA',
    'demands': '',
    'job': 'Marketing Manager',
    'height': '5\'7"',
    'about': 'A confident and goal-driven person.',
    'email': 'ava.williams@example.com',
    'fathers_name': 'Mr. Williams',
    'mothers_name': 'Mrs. Williams',
    'family_type': 'Nuclear family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'James Wilson',
    'address': 'Philadelphia',
    'age': '29',
    'gender': 'male',
    'cast': 'Hindu',
    'sub_cast': 'Kshatriya',
    'devak': 'Lion',
    'ras': 'Virgo',
    'gan': 'Elephant',
    'phone_number': '6789012345',
    'education': 'B.Tech (Civil Engineering)',
    'demands': '',
    'job': 'Civil Engineer',
    'height': '6\'0"',
    'about': 'A hardworking and focused individual.',
    'email': 'james.wilson@example.com',
    'fathers_name': 'Mr. Wilson',
    'mothers_name': 'Mrs. Wilson',
    'family_type': 'Joint family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': 'https://example.com/video4.mp4',
    'full_name': 'Isabella Martinez',
    'address': 'San Antonio',
    'age': '23',
    'gender': 'female',
    'cast': 'Muslim',
    'sub_cast': 'Shia',
    'devak': 'Star',
    'ras': 'Libra',
    'gan': 'Peacock',
    'phone_number': '7890123456',
    'education': 'BBA',
    'demands': 'Looking for a partner who is understanding',
    'job': 'Business Analyst',
    'height': '5\'3"',
    'about': 'A strategic thinker and compassionate person.',
    'email': 'isabella.martinez@example.com',
    'fathers_name': 'Mr. Martinez',
    'mothers_name': 'Mrs. Martinez',
    'family_type': 'Nuclear family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'Elijah Anderson',
    'address': 'San Diego',
    'age': '26',
    'gender': 'male',
    'cast': 'Christian',
    'sub_cast': 'Catholic',
    'devak': 'Olive Tree',
    'ras': 'Scorpio',
    'gan': 'Bear',
    'phone_number': '8901234567',
    'education': 'M.S. (Computer Science)',
    'demands': 'Open to relocating for the right partner',
    'job': 'Software Developer',
    'height': '5\'10"',
    'about': 'An adventurous and tech-savvy individual.',
    'email': 'elijah.anderson@example.com',
    'fathers_name': 'Mr. Anderson',
    'mothers_name': 'Mrs. Anderson',
    'family_type': 'Joint family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'Mia Thomas',
    'address': 'Dallas',
    'age': '22',
    'gender': 'female',
    'cast': 'Hindu',
    'sub_cast': 'Brahmin',
    'devak': 'Peepal Tree',
    'ras': 'Sagittarius',
    'gan': 'Lion',
    'phone_number': '9012345678',
    'education': 'B.Com',
    'demands': 'Seeking a family-oriented partner',
    'job': 'Accountant',
    'height': '5\'4"',
    'about': 'A warm and organized individual.',
    'email': 'mia.thomas@example.com',
    'fathers_name': 'Mr. Thomas',
    'mothers_name': 'Mrs. Thomas',
    'family_type': 'Nuclear family',
  },
  // Continue adding the next 10 users similarly
];
